### ISSUE TITLE
店舗や施設やイベントの混雑状況を「赤」「黄」「青」のカラーでビジュアル的に表現したい。

### ISSUE THREAD

**Issue by poba1031** [ww2or3ww/near-near-map-web#59]
店舗や施設やイベントの混雑状況を「赤」「黄」「青」のカラーでビジュアル的に表現したい。

場所の特性やニーズに応じて情報を選択して入手し表現できるといいな。

例
①IoTカメラや画像処理を使い完全自動化で表現（投資が必要）
②アプリ等で人の手で混雑情報を入力・発信し表現
③パブリックビーコンを入手して表現

**Comment by ww2or3ww** [comment]
やりましょう！(台本チラッ

**Comment by poba1031** [comment]
お願いします！

2020-06-11 21:54 GMT+09:00, w2or3w <notifications@github.com>:

**Comment by ww2or3ww** [comment]
close #74
